services:
  - type: web
    name: expressjs-app
    env: node
    region: oregon  # Yoki yaqin regioningizni tanlang
    buildCommand: npm install --build-from-source
    startCommand: npm start
    plan: free  # Yoki `starter` yoki pullik reja
    autoDeploy: true
    healthCheckPath: /
    disk:
      mountPath: /data
      sizeGb: 1  # SQLite ma’lumotlar uchun saqlash joyi
