name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main # Faqatgina `main` branchda ishlaydi
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub repository'dan kodlarni yuklash
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js o'rnatish
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Paketlarni o'rnatish
      - name: Install dependencies
        run: npm install

      # 4. Testlarni ishga tushirish
      - name: Run tests
        run: npm test

      # 5. Build yaratish (ixtiyoriy)
      - name: Build the project
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build # Build muvaffaqiyatli bo'lishi shart

    steps:
      # 1. SSH orqali serverga ulanib, fayllarni yuklash
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: 22
          script: |
            cd /path/to/project
            git pull origin main
            docker-compose down
            docker-compose up -d
